"""Add timestamp to booking

Revision ID: 089028007b70
Revises: c3ad4ce56068
Create Date: 2024-07-12 16:39:13.441373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '089028007b70'
down_revision = 'c3ad4ce56068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
